### ISSUE TITLE
Double digit rooms don't work with exit command

### ISSUE THREAD

**Issue by MolSnoo** [MolSnoo/Alter-Ego#61]
If there are numbered rooms that go in order from 1 into the double digits, the exit command (and likely others) will be unable to find the exit.

Example:
```
.unlock dorm-12 DOOR
Error: Couldn't execute command "unlock dorm-12 DOOR". Couldn't find exit "2 DOOR" in dorm-1.
```

**Comment by cbaker33** [comment]
Line 37 of exit_bot.js is causing this. The startsWith function is matching with the "dorm-1" part of "dorm-12." The "correct" way to fix it is probably to fully match the room name, but you can also just flip the for loop around so it starts from the largest number room and decrements toward 1. Longer room names won't be matched with shorter room names via startsWith.
